FROM python:3
ENV PYTHONUNBUFFERED 1
RUN pip install pandas
RUN pip install pandasql
RUN pip install numpy
RUN pip install sklearn
RUN pip install matplotlib
RUN pip install plotly
RUN pip install seaborn
RUN pip install scipy
RUN pip install statsmodels
RUN pip install yfinance
RUN pip install yahoo_finance_api2
RUN pip install yahoo_fin
RUN pip install pandas_datareader
RUN pip install requests_html
RUN pip install psycopg2